<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU5w8O8F\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU5w8O8F/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU5w8O8F.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU5w8O8F\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerU5w8O8F\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'U5w8O8F',
    'container.build_id' => '86dcfaf9',
    'container.build_time' => 1582481807,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU5w8O8F');
