<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXf1hQQh\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXf1hQQh/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXf1hQQh.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXf1hQQh\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXf1hQQh\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Xf1hQQh',
    'container.build_id' => 'b3ab072b',
    'container.build_time' => 1582481014,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXf1hQQh');
